---
driver:
  name: vagrant
  vm_hostname: false
  #vm_hostname: arista
  provision: true

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: vEOS_4.15.3F
    driver:
      vagrantfiles:
        - vagrantfiles/veos.rb
  - name: vEOS-4.16.7M
    driver:
      vagrantfiles:
        - vagrantfiles/veos.rb

suites:
  - name: default
    run_list:
      - recipe[eos::default]
    attributes:
